### ISSUE TITLE
Welcome bot has broken link to celebration image

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery-adapter-library#3]
**Description**
See the screenshot and this comment as an example of the issue - https://github.com/layer5io/meshery-adapter-library/pull/2#issuecomment-705114834

An issue lie somewhere between this config - https://github.com/layer5io/meshery-adapter-library/blob/cdeaac08801c9f128dd88cee2b4e5d5005c2c1a0/.github/config.yml#L20 and the location of the image in the `.github/welcome` folder

**Expected Behavior**
See this as an example of what should happen - https://github.com/layer5io/layer5/pull/691#issuecomment-683525292

**Screenshots**
<img width="941" alt="Screen Shot 2020-10-07 at 1 25 38 PM" src="https://user-images.githubusercontent.com/7570704/95372064-a7ec4180-08a0-11eb-85a1-95338adcda45.png">

**Comment by ocean** [comment]
I'll take a look at this 😃

**Comment by leecalcote** [comment]
Thank you, @ocean
