### ISSUE TITLE
Incluster Configure issues on adapters

### ISSUE THREAD

**Issue by kumarabd** [layer5io/meshery-adapter-library#42]
**Description**
Adapters doesn't get initialised when deployed In-Cluster

**Logs**
Istio:
```time="2021-04-27T12:37:17Z" level=error msg="Error creating adapter instance.Error validating kubeconfig.none of the auth infos are valid either the certificate path is invalid or is inaccessible" app=istio-adaptor code=1001 probable-cause=None severity=1 short-description=None suggested-remediation=None```

OSM:
```time="2021-04-27T12:49:58Z" level=warning msg="unable to type cast clusters to a map array"```

**Comment by leecalcote** [comment]
@Aisuko, I wonder if you might be able to take a crack at this one.

**Comment by utkarsh-pro** [comment]
@leecalcote PR #44 fixed this issue
